version: '3.4'

services:
  docker example 1:
    image: docker example 1
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]